import type {
  Pipeline,
  Lead,
  Contact,
  Conversation,
  Message,
  DashboardStats,
  FunnelData,
  TeamMember,
  TeamMemberStats,
  Appointment,
  AISuggestion,
  AIInsight,
  Tag,
  CustomField,
} from "."

// ── Helpers ─────────────────────────────────────────────────────

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

function hoursAgo(n: number): string {
  const d = new Date()
  d.setHours(d.getHours() - n)
  return d.toISOString()
}

function futureHours(n: number): string {
  const d = new Date()
  d.setHours(d.getHours() + n)
  return d.toISOString()
}

function futureDays(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString()
}

// ── Team Members ────────────────────────────────────────────────

export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    name: "Carlos Mendes",
    email: "carlos@techvendas.com",
    avatar: undefined,
    role: "admin",
    isActive: true,
    joinedAt: daysAgo(365),
  },
  {
    id: "tm-2",
    name: "Ana Beatriz Silva",
    email: "ana@techvendas.com",
    avatar: undefined,
    role: "gestor",
    isActive: true,
    joinedAt: daysAgo(300),
  },
  {
    id: "tm-3",
    name: "Rafael Oliveira",
    email: "rafael@techvendas.com",
    avatar: undefined,
    role: "closer",
    isActive: true,
    joinedAt: daysAgo(200),
  },
  {
    id: "tm-4",
    name: "Juliana Costa",
    email: "juliana@techvendas.com",
    avatar: undefined,
    role: "closer",
    isActive: true,
    joinedAt: daysAgo(150),
  },
  {
    id: "tm-5",
    name: "Pedro Henrique Santos",
    email: "pedro@techvendas.com",
    avatar: undefined,
    role: "sdr",
    isActive: true,
    joinedAt: daysAgo(90),
  },
]

// ── Pipelines ───────────────────────────────────────────────────

export const mockPipelines: Pipeline[] = [
  {
    id: "pipe-1",
    name: "Pré-qualificação",
    description: "Pipeline de entrada e qualificação de leads",
    isDefault: true,
    createdAt: daysAgo(180),
    stages: [
      {
        id: "pipe-1-s1",
        name: "Novo Lead",
        color: "#6366f1",
        order: 0,
        description: "Lead acabou de entrar no sistema",
        objective: "Fazer o primeiro contato em até 5 minutos",
        kpis: ["Tempo de primeiro contato", "Taxa de resposta"],
        responsibleRole: "sdr",
        automationRules: [
          {
            id: "ar-1",
            trigger: "form_submit",
            action: "send_message",
            config: { template: "welcome_msg" },
          },
        ],
      },
      {
        id: "pipe-1-s2",
        name: "Primeiro Contato",
        color: "#8b5cf6",
        order: 1,
        description: "SDR fez o primeiro contato com o lead",
        objective: "Qualificar o lead com perguntas SPIN",
        kpis: ["Taxa de qualificação", "Tempo médio no estágio"],
        responsibleRole: "sdr",
        automationRules: [
          {
            id: "ar-2",
            trigger: "whatsapp_reply",
            action: "update_field",
            config: { field: "lastInteraction", value: "now" },
          },
        ],
      },
      {
        id: "pipe-1-s3",
        name: "Qualificado",
        color: "#06b6d4",
        order: 2,
        description: "Lead passou na qualificação e está pronto para proposta",
        objective: "Agendar reunião de demonstração",
        kpis: ["Taxa de agendamento", "Score médio"],
        responsibleRole: "sdr",
        automationRules: [
          {
            id: "ar-3",
            trigger: "manual",
            action: "assign_closer",
            config: { roundRobin: true },
          },
        ],
      },
      {
        id: "pipe-1-s4",
        name: "Agendado",
        color: "#10b981",
        order: 3,
        description: "Reunião de demonstração agendada",
        objective: "Garantir presença e preparar materiais",
        kpis: ["Taxa de comparecimento", "No-show rate"],
        responsibleRole: "closer",
        automationRules: [
          {
            id: "ar-4",
            trigger: "no_show",
            action: "create_task",
            config: { task: "Reagendar reunião com lead" },
          },
        ],
      },
    ],
  },
  {
    id: "pipe-2",
    name: "Vendas",
    description: "Pipeline principal de vendas e fechamento",
    isDefault: false,
    createdAt: daysAgo(180),
    stages: [
      {
        id: "pipe-2-s1",
        name: "Reunião Realizada",
        color: "#f59e0b",
        order: 0,
        description: "Demonstração ou reunião concluída",
        objective: "Enviar proposta comercial em até 24h",
        kpis: ["Tempo de envio de proposta"],
        responsibleRole: "closer",
        automationRules: [],
      },
      {
        id: "pipe-2-s2",
        name: "Proposta Enviada",
        color: "#f97316",
        order: 1,
        description: "Proposta enviada e aguardando retorno",
        objective: "Fazer follow-up em 48h se sem resposta",
        kpis: ["Taxa de abertura", "Tempo de resposta"],
        responsibleRole: "closer",
        automationRules: [
          {
            id: "ar-5",
            trigger: "scheduled",
            action: "send_message",
            config: { delayHours: 48, template: "followup_proposta" },
          },
        ],
      },
      {
        id: "pipe-2-s3",
        name: "Negociação",
        color: "#ef4444",
        order: 2,
        description: "Em fase de negociação de preço ou escopo",
        objective: "Fechar acordo dentro de 7 dias",
        kpis: ["Desconto médio", "Taxa de fechamento"],
        responsibleRole: "closer",
        automationRules: [],
      },
      {
        id: "pipe-2-s4",
        name: "Contrato",
        color: "#22c55e",
        order: 3,
        description: "Contrato em assinatura",
        objective: "Confirmar assinatura e pagamento",
        kpis: ["Tempo de assinatura"],
        responsibleRole: "closer",
        automationRules: [
          {
            id: "ar-6",
            trigger: "payment_webhook",
            action: "move_stage",
            targetStageId: "pipe-2-s5",
            config: {},
          },
        ],
      },
      {
        id: "pipe-2-s5",
        name: "Ganho",
        color: "#16a34a",
        order: 4,
        description: "Venda concluída com sucesso",
        objective: "Iniciar onboarding do cliente",
        kpis: ["Ticket médio", "Tempo de ciclo total"],
        responsibleRole: "gestor",
        automationRules: [
          {
            id: "ar-7",
            trigger: "manual",
            action: "notify",
            config: { channel: "slack", message: "Nova venda fechada!" },
          },
        ],
      },
      {
        id: "pipe-2-s6",
        name: "Perdido",
        color: "#dc2626",
        order: 5,
        description: "Negócio perdido",
        objective: "Registrar motivo da perda para análise",
        kpis: ["Motivo de perda"],
        responsibleRole: "gestor",
        automationRules: [],
      },
    ],
  },
  {
    id: "pipe-3",
    name: "Suporte Pós-Venda",
    description: "Pipeline de atendimento ao cliente existente",
    isDefault: false,
    createdAt: daysAgo(120),
    stages: [
      {
        id: "pipe-3-s1",
        name: "Novo Chamado",
        color: "#6366f1",
        order: 0,
        description: "Solicitação recebida do cliente",
        objective: "Responder em até 2 horas",
        kpis: ["Tempo de resposta"],
        responsibleRole: "sdr",
        automationRules: [],
      },
      {
        id: "pipe-3-s2",
        name: "Em Atendimento",
        color: "#f59e0b",
        order: 1,
        description: "Chamado em andamento",
        objective: "Resolver o problema do cliente",
        kpis: ["Tempo de resolução"],
        responsibleRole: "closer",
        automationRules: [],
      },
      {
        id: "pipe-3-s3",
        name: "Aguardando Cliente",
        color: "#8b5cf6",
        order: 2,
        description: "Aguardando retorno ou informação do cliente",
        objective: "Fazer follow-up se sem resposta em 24h",
        kpis: ["Tempo de espera"],
        responsibleRole: "closer",
        automationRules: [
          {
            id: "ar-8",
            trigger: "scheduled",
            action: "send_message",
            config: { delayHours: 24, template: "followup_suporte" },
          },
        ],
      },
      {
        id: "pipe-3-s4",
        name: "Resolvido",
        color: "#22c55e",
        order: 3,
        description: "Chamado resolvido com sucesso",
        objective: "Enviar pesquisa de satisfação",
        kpis: ["NPS", "CSAT"],
        responsibleRole: "sdr",
        automationRules: [
          {
            id: "ar-9",
            trigger: "manual",
            action: "send_message",
            config: { template: "pesquisa_nps" },
          },
        ],
      },
    ],
  },
]

// ── Leads ───────────────────────────────────────────────────────

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Marcos Ferreira",
    email: "marcos@empresa.com.br",
    phone: "+5511999001001",
    company: "Ferreira Consultoria",
    value: 15000,
    score: 85,
    status: "qualified",
    priority: "high",
    channel: "whatsapp",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s3",
    assignedTo: "tm-5",
    tags: ["enterprise", "urgente"],
    customFields: { setor: "Tecnologia", funcionários: 50 },
    isLocked: false,
    lastInteraction: hoursAgo(2),
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(2),
  },
  {
    id: "lead-2",
    name: "Camila Rodrigues",
    email: "camila@lojadigital.com.br",
    phone: "+5521988002002",
    company: "Loja Digital LTDA",
    value: 8500,
    score: 72,
    status: "proposal",
    priority: "medium",
    channel: "instagram",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s2",
    assignedTo: "tm-3",
    tags: ["ecommerce"],
    customFields: { setor: "Varejo", funcionários: 15 },
    isLocked: false,
    lastInteraction: hoursAgo(6),
    createdAt: daysAgo(12),
    updatedAt: hoursAgo(6),
  },
  {
    id: "lead-3",
    name: "Roberto Almeida",
    email: "roberto@construtecno.com.br",
    phone: "+5531977003003",
    company: "ConstruTecno",
    value: 32000,
    score: 92,
    status: "negotiation",
    priority: "urgent",
    channel: "form",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s3",
    assignedTo: "tm-3",
    tags: ["enterprise", "construção"],
    customFields: { setor: "Construção Civil", funcionários: 200 },
    isLocked: true,
    lockedBy: "tm-3",
    lastInteraction: hoursAgo(1),
    createdAt: daysAgo(20),
    updatedAt: hoursAgo(1),
  },
  {
    id: "lead-4",
    name: "Fernanda Lima",
    email: "fernanda@beautycare.com.br",
    phone: "+5511966004004",
    company: "Beauty Care",
    value: 4200,
    score: 55,
    status: "contacted",
    priority: "medium",
    channel: "whatsapp",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s2",
    assignedTo: "tm-5",
    tags: ["pme", "beleza"],
    customFields: { setor: "Beleza", funcionários: 8 },
    isLocked: false,
    lastInteraction: hoursAgo(24),
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(24),
  },
  {
    id: "lead-5",
    name: "Thiago Nascimento",
    email: "thiago@startupflow.io",
    phone: "+5541955005005",
    company: "StartupFlow",
    value: 22000,
    score: 78,
    status: "qualified",
    priority: "high",
    channel: "telegram",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s4",
    assignedTo: "tm-4",
    tags: ["saas", "startup"],
    customFields: { setor: "SaaS", funcionários: 30 },
    isLocked: false,
    lastInteraction: hoursAgo(4),
    createdAt: daysAgo(8),
    updatedAt: hoursAgo(4),
  },
  {
    id: "lead-6",
    name: "Patrícia Gomes",
    phone: "+5511944006006",
    company: "PG Advocacia",
    value: 6800,
    score: 40,
    status: "new",
    priority: "low",
    channel: "form",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s1",
    tags: ["jurídico"],
    customFields: { setor: "Jurídico", funcionários: 5 },
    isLocked: false,
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: "lead-7",
    name: "Lucas Martins",
    email: "lucas@agenciacriativa.com.br",
    phone: "+5521933007007",
    company: "Agência Criativa",
    value: 11500,
    score: 68,
    status: "proposal",
    priority: "medium",
    channel: "instagram",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s2",
    assignedTo: "tm-4",
    tags: ["marketing", "agência"],
    customFields: { setor: "Marketing Digital", funcionários: 20 },
    isLocked: false,
    lastInteraction: hoursAgo(8),
    createdAt: daysAgo(15),
    updatedAt: hoursAgo(8),
  },
  {
    id: "lead-8",
    name: "Renata Souza",
    email: "renata@educatech.com.br",
    phone: "+5511922008008",
    company: "EducaTech",
    value: 18000,
    score: 81,
    status: "qualified",
    priority: "high",
    channel: "whatsapp",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s1",
    assignedTo: "tm-3",
    tags: ["educação", "enterprise"],
    customFields: { setor: "Educação", funcionários: 80 },
    isLocked: false,
    lastInteraction: hoursAgo(12),
    createdAt: daysAgo(10),
    updatedAt: hoursAgo(12),
  },
  {
    id: "lead-9",
    name: "Diego Barbosa",
    phone: "+5531911009009",
    value: 3200,
    score: 35,
    status: "new",
    priority: "low",
    channel: "webhook",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s1",
    tags: ["frio"],
    customFields: {},
    isLocked: false,
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: "lead-10",
    name: "Amanda Pereira",
    email: "amanda@fitlife.com.br",
    phone: "+5541900010010",
    company: "FitLife Academia",
    value: 7600,
    score: 63,
    status: "contacted",
    priority: "medium",
    channel: "manual",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s2",
    assignedTo: "tm-5",
    tags: ["fitness", "pme"],
    customFields: { setor: "Saúde e Fitness", funcionários: 12 },
    isLocked: false,
    lastInteraction: daysAgo(1),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "lead-11",
    name: "Gustavo Teixeira",
    email: "gustavo@farmaconecta.com.br",
    phone: "+5511988011011",
    company: "FarmaConecta",
    value: 45000,
    score: 95,
    status: "won",
    priority: "urgent",
    channel: "whatsapp",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s5",
    assignedTo: "tm-3",
    tags: ["enterprise", "farma", "fechado"],
    customFields: { setor: "Farmacêutico", funcionários: 350 },
    isLocked: false,
    lastInteraction: daysAgo(2),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: "lead-12",
    name: "Isabela Carvalho",
    email: "isabela@modastyle.com.br",
    phone: "+5521977012012",
    company: "Moda Style",
    value: 5800,
    score: 20,
    status: "lost",
    priority: "low",
    channel: "instagram",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s6",
    assignedTo: "tm-4",
    tags: ["moda", "perdido"],
    customFields: { setor: "Moda", funcionários: 6, motivoPerda: "Preço" },
    isLocked: false,
    lastInteraction: daysAgo(10),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(10),
  },
  {
    id: "lead-13",
    name: "Felipe Araújo",
    email: "felipe@datainsight.com.br",
    phone: "+5511966013013",
    company: "DataInsight",
    value: 28000,
    score: 88,
    status: "negotiation",
    priority: "urgent",
    channel: "form",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s3",
    assignedTo: "tm-4",
    tags: ["dados", "enterprise"],
    customFields: { setor: "Análise de Dados", funcionários: 60 },
    isLocked: true,
    lockedBy: "tm-4",
    lastInteraction: hoursAgo(3),
    createdAt: daysAgo(18),
    updatedAt: hoursAgo(3),
  },
  {
    id: "lead-14",
    name: "Vanessa Moura",
    phone: "+5541955014014",
    company: "VM Contabilidade",
    value: 3800,
    score: 48,
    status: "new",
    priority: "low",
    channel: "whatsapp",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s1",
    tags: ["contabilidade"],
    customFields: { setor: "Contabilidade", funcionários: 4 },
    isLocked: false,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: "lead-15",
    name: "Bruno Fonseca",
    email: "bruno@logitrans.com.br",
    phone: "+5531944015015",
    company: "LogiTrans",
    value: 19500,
    score: 76,
    status: "proposal",
    priority: "high",
    channel: "telegram",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s2",
    assignedTo: "tm-3",
    tags: ["logística", "enterprise"],
    customFields: { setor: "Logística", funcionários: 120 },
    isLocked: false,
    lastInteraction: hoursAgo(10),
    createdAt: daysAgo(14),
    updatedAt: hoursAgo(10),
  },
  {
    id: "lead-16",
    name: "Carolina Farias",
    email: "carolina@greentech.eco.br",
    phone: "+5511933016016",
    company: "GreenTech Sustentável",
    value: 14000,
    score: 71,
    status: "contacted",
    priority: "medium",
    channel: "form",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s2",
    assignedTo: "tm-5",
    tags: ["sustentabilidade", "tech"],
    customFields: { setor: "Meio Ambiente", funcionários: 25 },
    isLocked: false,
    lastInteraction: daysAgo(2),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
  },
  {
    id: "lead-17",
    name: "Eduardo Pinto",
    email: "eduardo@agromax.com.br",
    phone: "+5562922017017",
    company: "AgroMax",
    value: 55000,
    score: 90,
    status: "negotiation",
    priority: "urgent",
    channel: "manual",
    pipelineId: "pipe-2",
    stageId: "pipe-2-s4",
    assignedTo: "tm-3",
    tags: ["agro", "enterprise", "vip"],
    customFields: { setor: "Agronegócio", funcionários: 500 },
    isLocked: true,
    lockedBy: "tm-3",
    lastInteraction: hoursAgo(2),
    createdAt: daysAgo(25),
    updatedAt: hoursAgo(2),
  },
  {
    id: "lead-18",
    name: "Natália Brito",
    email: "natalia@petshoplove.com.br",
    phone: "+5511911018018",
    company: "Pet Shop Love",
    value: 2800,
    score: 30,
    status: "contacted",
    priority: "low",
    channel: "instagram",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s2",
    tags: ["pet", "pme"],
    customFields: { setor: "Pet", funcionários: 3 },
    isLocked: false,
    lastInteraction: daysAgo(3),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },
  {
    id: "lead-19",
    name: "Ricardo Lopes",
    email: "ricardo@autoparts.com.br",
    phone: "+5531900019019",
    company: "AutoParts Brasil",
    value: 21000,
    score: 82,
    status: "qualified",
    priority: "high",
    channel: "whatsapp",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s3",
    assignedTo: "tm-5",
    tags: ["automotivo", "enterprise"],
    customFields: { setor: "Automotivo", funcionários: 90 },
    isLocked: false,
    lastInteraction: hoursAgo(5),
    createdAt: daysAgo(9),
    updatedAt: hoursAgo(5),
  },
  {
    id: "lead-20",
    name: "Simone Vieira",
    email: "simone@clinicavida.com.br",
    phone: "+5521988020020",
    company: "Clínica Vida",
    value: 9800,
    score: 65,
    status: "qualified",
    priority: "medium",
    channel: "whatsapp",
    pipelineId: "pipe-1",
    stageId: "pipe-1-s4",
    assignedTo: "tm-4",
    tags: ["saúde", "clínica"],
    customFields: { setor: "Saúde", funcionários: 18 },
    isLocked: false,
    lastInteraction: hoursAgo(7),
    createdAt: daysAgo(11),
    updatedAt: hoursAgo(7),
  },
]

// ── Contacts ────────────────────────────────────────────────────

export const mockContacts: Contact[] = [
  {
    id: "ct-1",
    name: "Marcos Ferreira",
    email: "marcos@empresa.com.br",
    phone: "+5511999001001",
    company: "Ferreira Consultoria",
    role: "CEO",
    source: "whatsapp",
    tags: ["enterprise", "urgente"],
    score: 85,
    lifecycleStage: "sql",
    customFields: { setor: "Tecnologia" },
    createdAt: daysAgo(30),
    updatedAt: hoursAgo(2),
  },
  {
    id: "ct-2",
    name: "Camila Rodrigues",
    email: "camila@lojadigital.com.br",
    phone: "+5521988002002",
    company: "Loja Digital LTDA",
    role: "Diretora de Marketing",
    source: "instagram",
    tags: ["ecommerce"],
    score: 72,
    lifecycleStage: "opportunity",
    customFields: { setor: "Varejo" },
    createdAt: daysAgo(45),
    updatedAt: hoursAgo(6),
  },
  {
    id: "ct-3",
    name: "Roberto Almeida",
    email: "roberto@construtecno.com.br",
    phone: "+5531977003003",
    company: "ConstruTecno",
    role: "Gerente de Operações",
    source: "form",
    tags: ["enterprise", "construção"],
    score: 92,
    lifecycleStage: "opportunity",
    customFields: { setor: "Construção Civil" },
    createdAt: daysAgo(60),
    updatedAt: hoursAgo(1),
  },
  {
    id: "ct-4",
    name: "Gustavo Teixeira",
    email: "gustavo@farmaconecta.com.br",
    phone: "+5511988011011",
    company: "FarmaConecta",
    role: "Diretor Comercial",
    source: "whatsapp",
    tags: ["enterprise", "farma", "fechado"],
    score: 95,
    lifecycleStage: "customer",
    customFields: { setor: "Farmacêutico" },
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },
  {
    id: "ct-5",
    name: "Eduardo Pinto",
    email: "eduardo@agromax.com.br",
    phone: "+5562922017017",
    company: "AgroMax",
    role: "CFO",
    source: "manual",
    tags: ["agro", "enterprise", "vip"],
    score: 90,
    lifecycleStage: "opportunity",
    customFields: { setor: "Agronegócio" },
    createdAt: daysAgo(50),
    updatedAt: hoursAgo(2),
  },
  {
    id: "ct-6",
    name: "Isabela Carvalho",
    email: "isabela@modastyle.com.br",
    phone: "+5521977012012",
    company: "Moda Style",
    role: "Proprietária",
    source: "instagram",
    tags: ["moda", "perdido"],
    score: 20,
    lifecycleStage: "churned",
    customFields: { setor: "Moda" },
    createdAt: daysAgo(60),
    updatedAt: daysAgo(10),
  },
]

// ── Conversations ───────────────────────────────────────────────

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    contactId: "ct-1",
    contactName: "Marcos Ferreira",
    contactPhone: "+5511999001001",
    channel: "whatsapp",
    status: "open",
    assignedTo: "tm-5",
    assignedName: "Pedro Henrique Santos",
    lastMessage: "Perfeito, vou analisar a proposta e retorno amanhã",
    lastMessageAt: hoursAgo(2),
    unreadCount: 1,
    labels: ["quente", "enterprise"],
    createdAt: daysAgo(5),
  },
  {
    id: "conv-2",
    contactId: "ct-2",
    contactName: "Camila Rodrigues",
    contactPhone: "+5521988002002",
    channel: "instagram",
    status: "waiting",
    assignedTo: "tm-3",
    assignedName: "Rafael Oliveira",
    lastMessage: "Obrigada pela demonstração! Vou falar com meu sócio",
    lastMessageAt: hoursAgo(6),
    unreadCount: 0,
    labels: ["ecommerce"],
    createdAt: daysAgo(12),
  },
  {
    id: "conv-3",
    contactId: "ct-3",
    contactName: "Roberto Almeida",
    contactPhone: "+5531977003003",
    channel: "whatsapp",
    status: "open",
    assignedTo: "tm-3",
    assignedName: "Rafael Oliveira",
    lastMessage: "Preciso que revisem o valor para 200 licenças",
    lastMessageAt: hoursAgo(1),
    unreadCount: 3,
    labels: ["enterprise", "negociação"],
    createdAt: daysAgo(20),
  },
  {
    id: "conv-4",
    contactId: "ct-4",
    contactName: "Gustavo Teixeira",
    contactPhone: "+5511988011011",
    channel: "whatsapp",
    status: "closed",
    assignedTo: "tm-3",
    assignedName: "Rafael Oliveira",
    lastMessage: "Contrato assinado! Quando começamos o onboarding?",
    lastMessageAt: daysAgo(2),
    unreadCount: 0,
    labels: ["fechado", "onboarding"],
    createdAt: daysAgo(45),
  },
  {
    id: "conv-5",
    contactId: "ct-5",
    contactName: "Eduardo Pinto",
    contactPhone: "+5562922017017",
    channel: "whatsapp",
    status: "open",
    assignedTo: "tm-3",
    assignedName: "Rafael Oliveira",
    lastMessage: "Conseguem incluir a integração com nosso ERP?",
    lastMessageAt: hoursAgo(2),
    unreadCount: 2,
    labels: ["enterprise", "vip", "integração"],
    createdAt: daysAgo(25),
  },
  {
    id: "conv-6",
    contactId: "ct-6",
    contactName: "Isabela Carvalho",
    contactPhone: "+5521977012012",
    channel: "instagram",
    status: "closed",
    assignedTo: "tm-4",
    assignedName: "Juliana Costa",
    lastMessage: "Infelizmente não temos orçamento agora. Obrigada!",
    lastMessageAt: daysAgo(10),
    unreadCount: 0,
    labels: ["perdido"],
    createdAt: daysAgo(30),
  },
  {
    id: "conv-7",
    contactId: "ct-1",
    contactName: "Fernanda Lima",
    contactPhone: "+5511966004004",
    channel: "whatsapp",
    status: "open",
    assignedTo: "tm-5",
    assignedName: "Pedro Henrique Santos",
    lastMessage: "Oi! Vi o anúncio de vocês no Instagram. Quero saber mais!",
    lastMessageAt: hoursAgo(24),
    unreadCount: 1,
    labels: ["beleza", "inbound"],
    createdAt: daysAgo(3),
  },
  {
    id: "conv-8",
    contactId: "ct-5",
    contactName: "Thiago Nascimento",
    contactPhone: "+5541955005005",
    channel: "telegram",
    status: "open",
    assignedTo: "tm-4",
    assignedName: "Juliana Costa",
    lastMessage: "A demo está confirmada para amanhã às 14h?",
    lastMessageAt: hoursAgo(4),
    unreadCount: 1,
    labels: ["saas", "demo"],
    createdAt: daysAgo(8),
  },
  {
    id: "conv-9",
    contactId: "ct-3",
    contactName: "Amanda Pereira",
    contactPhone: "+5541900010010",
    channel: "whatsapp",
    status: "waiting",
    assignedTo: "tm-5",
    assignedName: "Pedro Henrique Santos",
    lastMessage: "Vou conversar com minha sócia e te dou retorno",
    lastMessageAt: daysAgo(1),
    unreadCount: 0,
    labels: ["fitness"],
    createdAt: daysAgo(7),
  },
  {
    id: "conv-10",
    contactId: "ct-2",
    contactName: "Lucas Martins",
    contactPhone: "+5521933007007",
    channel: "instagram",
    status: "open",
    assignedTo: "tm-4",
    assignedName: "Juliana Costa",
    lastMessage: "Gostei da proposta. Podemos agendar uma call?",
    lastMessageAt: hoursAgo(8),
    unreadCount: 2,
    labels: ["agência", "marketing"],
    createdAt: daysAgo(15),
  },
  {
    id: "conv-11",
    contactId: "ct-4",
    contactName: "Renata Souza",
    contactPhone: "+5511922008008",
    channel: "whatsapp",
    status: "open",
    assignedTo: "tm-3",
    assignedName: "Rafael Oliveira",
    lastMessage: "A reunião foi ótima! Aguardo o material",
    lastMessageAt: hoursAgo(12),
    unreadCount: 0,
    labels: ["educação"],
    createdAt: daysAgo(10),
  },
  {
    id: "conv-12",
    contactId: "ct-5",
    contactName: "Bruno Fonseca",
    contactPhone: "+5531944015015",
    channel: "telegram",
    status: "waiting",
    assignedTo: "tm-3",
    assignedName: "Rafael Oliveira",
    lastMessage: "Preciso validar internamente. Te aviso até sexta",
    lastMessageAt: hoursAgo(10),
    unreadCount: 0,
    labels: ["logística"],
    createdAt: daysAgo(14),
  },
  {
    id: "conv-13",
    contactId: "ct-1",
    contactName: "Carolina Farias",
    contactPhone: "+5511933016016",
    channel: "whatsapp",
    status: "paused",
    assignedTo: "tm-5",
    assignedName: "Pedro Henrique Santos",
    lastMessage: "Estou em viagem, podemos conversar semana que vem?",
    lastMessageAt: daysAgo(2),
    unreadCount: 0,
    labels: ["sustentabilidade"],
    createdAt: daysAgo(6),
  },
  {
    id: "conv-14",
    contactId: "ct-3",
    contactName: "Ricardo Lopes",
    contactPhone: "+5531900019019",
    channel: "whatsapp",
    status: "open",
    assignedTo: "tm-5",
    assignedName: "Pedro Henrique Santos",
    lastMessage: "Quando podemos agendar a demonstração?",
    lastMessageAt: hoursAgo(5),
    unreadCount: 1,
    labels: ["automotivo", "qualificado"],
    createdAt: daysAgo(9),
  },
  {
    id: "conv-15",
    contactId: "ct-2",
    contactName: "Simone Vieira",
    contactPhone: "+5521988020020",
    channel: "whatsapp",
    status: "open",
    assignedTo: "tm-4",
    assignedName: "Juliana Costa",
    lastMessage: "A clínica precisa de algo que integre com nosso sistema",
    lastMessageAt: hoursAgo(7),
    unreadCount: 1,
    labels: ["saúde", "integração"],
    createdAt: daysAgo(11),
  },
]

// ── Messages ────────────────────────────────────────────────────

export const mockMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1-1",
      conversationId: "conv-1",
      content: "Olá Marcos! Sou o Pedro da Tech Vendas. Vi que você se cadastrou no nosso site. Como posso ajudar?",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Pedro Henrique Santos",
      timestamp: daysAgo(5),
    },
    {
      id: "msg-1-2",
      conversationId: "conv-1",
      content: "Olá Pedro! Estou procurando uma solução de CRM para minha consultoria. Temos 50 funcionários e precisamos de algo robusto.",
      type: "text",
      direction: "inbound",
      status: "read",
      senderName: "Marcos Ferreira",
      timestamp: daysAgo(5),
    },
    {
      id: "msg-1-3",
      conversationId: "conv-1",
      content: "Ótimo! Temos planos enterprise que se encaixam perfeitamente. Posso agendar uma demonstração personalizada?",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Pedro Henrique Santos",
      timestamp: daysAgo(4),
    },
    {
      id: "msg-1-4",
      conversationId: "conv-1",
      content: "Sim, pode ser. Qual horário você tem disponível essa semana?",
      type: "text",
      direction: "inbound",
      status: "read",
      senderName: "Marcos Ferreira",
      timestamp: daysAgo(4),
    },
    {
      id: "msg-1-5",
      conversationId: "conv-1",
      content: "Temos quinta-feira às 14h ou sexta às 10h. Qual fica melhor?",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Pedro Henrique Santos",
      timestamp: daysAgo(3),
    },
    {
      id: "msg-1-6",
      conversationId: "conv-1",
      content: "Quinta às 14h está perfeito!",
      type: "text",
      direction: "inbound",
      status: "read",
      senderName: "Marcos Ferreira",
      timestamp: daysAgo(3),
    },
    {
      id: "msg-1-7",
      conversationId: "conv-1",
      content: "Marcos, estou enviando a proposta comercial conforme alinhado na reunião. Qualquer dúvida estou à disposição!",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Pedro Henrique Santos",
      timestamp: daysAgo(1),
    },
    {
      id: "msg-1-8",
      conversationId: "conv-1",
      content: "proposta_techvendas_ferreira.pdf",
      type: "document",
      direction: "outbound",
      status: "delivered",
      senderName: "Pedro Henrique Santos",
      timestamp: daysAgo(1),
      metadata: { fileName: "proposta_techvendas_ferreira.pdf", fileSize: "2.4MB" },
    },
    {
      id: "msg-1-9",
      conversationId: "conv-1",
      content: "Perfeito, vou analisar a proposta e retorno amanhã",
      type: "text",
      direction: "inbound",
      status: "delivered",
      senderName: "Marcos Ferreira",
      timestamp: hoursAgo(2),
    },
  ],
  "conv-3": [
    {
      id: "msg-3-1",
      conversationId: "conv-3",
      content: "Roberto, bom dia! Segue o detalhamento do plano enterprise para 200 licenças conforme solicitado.",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Rafael Oliveira",
      timestamp: daysAgo(3),
    },
    {
      id: "msg-3-2",
      conversationId: "conv-3",
      content: "Obrigado Rafael. Estou analisando com o financeiro. O valor para 200 licenças ficou acima do nosso orçamento.",
      type: "text",
      direction: "inbound",
      status: "read",
      senderName: "Roberto Almeida",
      timestamp: daysAgo(2),
    },
    {
      id: "msg-3-3",
      conversationId: "conv-3",
      content: "Entendo perfeitamente. Consigo trabalhar uma condição especial para contratos anuais. Posso enviar uma nova proposta?",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Rafael Oliveira",
      timestamp: daysAgo(1),
    },
    {
      id: "msg-3-4",
      conversationId: "conv-3",
      content: "Sim, por favor. Preciso que revisem o valor para 200 licenças",
      type: "text",
      direction: "inbound",
      status: "delivered",
      senderName: "Roberto Almeida",
      timestamp: hoursAgo(1),
    },
  ],
  "conv-5": [
    {
      id: "msg-5-1",
      conversationId: "conv-5",
      content: "Eduardo, boa tarde! A integração com SAP está incluída no plano enterprise. Gostaria de saber mais detalhes sobre o ERP de vocês.",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Rafael Oliveira",
      timestamp: daysAgo(5),
    },
    {
      id: "msg-5-2",
      conversationId: "conv-5",
      content: "Nós usamos o TOTVS Protheus. A integração precisa ser bidirecional para sincronizar clientes e pedidos.",
      type: "text",
      direction: "inbound",
      status: "read",
      senderName: "Eduardo Pinto",
      timestamp: daysAgo(4),
    },
    {
      id: "msg-5-3",
      conversationId: "conv-5",
      content: "Perfeito, temos um conector nativo para TOTVS Protheus. Vou preparar uma PoC para vocês visualizarem o fluxo.",
      type: "text",
      direction: "outbound",
      status: "read",
      senderName: "Rafael Oliveira",
      timestamp: daysAgo(3),
    },
    {
      id: "msg-5-4",
      conversationId: "conv-5",
      content: "Conseguem incluir a integração com nosso ERP?",
      type: "text",
      direction: "inbound",
      status: "delivered",
      senderName: "Eduardo Pinto",
      timestamp: hoursAgo(2),
    },
  ],
}

// ── Dashboard Stats ─────────────────────────────────────────────

export const mockDashboardStats: DashboardStats = {
  totalLeads: 247,
  totalLeadsChange: 12.5,
  activeDeals: 38,
  activeDealsChange: 8.3,
  conversionRate: 24.6,
  conversionRateChange: 3.2,
  totalRevenue: 287450,
  totalRevenueChange: 18.7,
  avgResponseTime: "4min 32s",
  avgResponseTimeChange: -15.2,
}

// ── Funnel Data ─────────────────────────────────────────────────

export const mockFunnelData: FunnelData[] = [
  {
    stageId: "pipe-1-s1",
    stageName: "Novo Lead",
    count: 45,
    value: 180000,
    conversionRate: 100,
    avgTimeInStage: "2h 15min",
    dropoffRate: 0,
  },
  {
    stageId: "pipe-1-s2",
    stageName: "Primeiro Contato",
    count: 38,
    value: 152000,
    conversionRate: 84.4,
    avgTimeInStage: "1d 8h",
    dropoffRate: 15.6,
  },
  {
    stageId: "pipe-1-s3",
    stageName: "Qualificado",
    count: 28,
    value: 112000,
    conversionRate: 73.7,
    avgTimeInStage: "2d 4h",
    dropoffRate: 26.3,
  },
  {
    stageId: "pipe-2-s1",
    stageName: "Reunião Realizada",
    count: 22,
    value: 88000,
    conversionRate: 78.6,
    avgTimeInStage: "1d 12h",
    dropoffRate: 21.4,
  },
  {
    stageId: "pipe-2-s2",
    stageName: "Proposta Enviada",
    count: 18,
    value: 72000,
    conversionRate: 81.8,
    avgTimeInStage: "3d 6h",
    dropoffRate: 18.2,
  },
  {
    stageId: "pipe-2-s3",
    stageName: "Negociação",
    count: 12,
    value: 48000,
    conversionRate: 66.7,
    avgTimeInStage: "4d 18h",
    dropoffRate: 33.3,
  },
  {
    stageId: "pipe-2-s5",
    stageName: "Ganho",
    count: 8,
    value: 287450,
    conversionRate: 66.7,
    avgTimeInStage: "-",
    dropoffRate: 33.3,
  },
]

// ── Team Member Stats ───────────────────────────────────────────

export const mockTeamMemberStats: TeamMemberStats[] = [
  {
    id: "tm-1",
    name: "Carlos Mendes",
    role: "admin",
    dealsWon: 0,
    dealsLost: 0,
    totalValue: 0,
    conversionRate: 0,
    avgResponseTime: "-",
    slaCompliance: 100,
  },
  {
    id: "tm-2",
    name: "Ana Beatriz Silva",
    role: "gestor",
    dealsWon: 5,
    dealsLost: 2,
    totalValue: 85000,
    conversionRate: 71.4,
    avgResponseTime: "3min 45s",
    slaCompliance: 95,
  },
  {
    id: "tm-3",
    name: "Rafael Oliveira",
    role: "closer",
    dealsWon: 12,
    dealsLost: 4,
    totalValue: 198000,
    conversionRate: 75.0,
    avgResponseTime: "5min 12s",
    slaCompliance: 88,
  },
  {
    id: "tm-4",
    name: "Juliana Costa",
    role: "closer",
    dealsWon: 8,
    dealsLost: 3,
    totalValue: 124000,
    conversionRate: 72.7,
    avgResponseTime: "4min 30s",
    slaCompliance: 91,
  },
  {
    id: "tm-5",
    name: "Pedro Henrique Santos",
    role: "sdr",
    dealsWon: 0,
    dealsLost: 0,
    totalValue: 0,
    conversionRate: 0,
    avgResponseTime: "2min 18s",
    slaCompliance: 97,
  },
]

// ── Appointments ────────────────────────────────────────────────

export const mockAppointments: Appointment[] = [
  {
    id: "apt-1",
    leadId: "lead-5",
    leadName: "Thiago Nascimento",
    closerId: "tm-4",
    closerName: "Juliana Costa",
    type: "demo",
    status: "confirmed",
    scheduledAt: futureHours(4),
    duration: 60,
    notes: "Demonstração completa do módulo de automação para StartupFlow",
  },
  {
    id: "apt-2",
    leadId: "lead-20",
    leadName: "Simone Vieira",
    closerId: "tm-4",
    closerName: "Juliana Costa",
    type: "call",
    status: "scheduled",
    scheduledAt: futureHours(26),
    duration: 30,
    notes: "Alinhar necessidades da clínica e integração com sistema médico",
  },
  {
    id: "apt-3",
    leadId: "lead-3",
    leadName: "Roberto Almeida",
    closerId: "tm-3",
    closerName: "Rafael Oliveira",
    type: "meeting",
    status: "confirmed",
    scheduledAt: futureHours(48),
    duration: 45,
    notes: "Reunião de negociação de preço para 200 licenças - ConstruTecno",
  },
  {
    id: "apt-4",
    leadId: "lead-17",
    leadName: "Eduardo Pinto",
    closerId: "tm-3",
    closerName: "Rafael Oliveira",
    type: "demo",
    status: "confirmed",
    scheduledAt: futureDays(3),
    duration: 90,
    notes: "PoC da integração TOTVS Protheus para AgroMax - presença do time de TI",
  },
  {
    id: "apt-5",
    leadId: "lead-19",
    leadName: "Ricardo Lopes",
    closerId: "tm-5",
    closerName: "Pedro Henrique Santos",
    type: "demo",
    status: "scheduled",
    scheduledAt: futureDays(2),
    duration: 60,
    notes: "Primeira demonstração para AutoParts Brasil - foco em gestão de leads",
  },
  {
    id: "apt-6",
    leadId: "lead-11",
    leadName: "Gustavo Teixeira",
    closerId: "tm-3",
    closerName: "Rafael Oliveira",
    type: "follow_up",
    status: "completed",
    scheduledAt: daysAgo(3),
    duration: 30,
    notes: "Follow-up pós-venda FarmaConecta - início do onboarding",
  },
  {
    id: "apt-7",
    leadId: "lead-12",
    leadName: "Isabela Carvalho",
    closerId: "tm-4",
    closerName: "Juliana Costa",
    type: "call",
    status: "no_show",
    scheduledAt: daysAgo(11),
    duration: 30,
    notes: "Lead não atendeu - marcou como sem interesse posterior",
  },
  {
    id: "apt-8",
    leadId: "lead-1",
    leadName: "Marcos Ferreira",
    closerId: "tm-5",
    closerName: "Pedro Henrique Santos",
    type: "follow_up",
    status: "scheduled",
    scheduledAt: futureDays(1),
    duration: 15,
    notes: "Follow-up sobre a proposta enviada ontem",
  },
  {
    id: "apt-9",
    leadId: "lead-13",
    leadName: "Felipe Araújo",
    closerId: "tm-4",
    closerName: "Juliana Costa",
    type: "meeting",
    status: "rescheduled",
    scheduledAt: futureDays(5),
    duration: 60,
    notes: "Reunião remarcada a pedido do lead - negociação final DataInsight",
  },
  {
    id: "apt-10",
    leadId: "lead-15",
    leadName: "Bruno Fonseca",
    closerId: "tm-3",
    closerName: "Rafael Oliveira",
    type: "call",
    status: "scheduled",
    scheduledAt: futureDays(4),
    duration: 30,
    notes: "Follow-up proposta LogiTrans - aguardando validação interna",
  },
]

// ── AI Suggestions ──────────────────────────────────────────────

export const mockAISuggestions: AISuggestion[] = [
  {
    id: "ai-s-1",
    type: "response",
    content: "Com base no histórico do lead, sugiro mencionar o caso de sucesso da FarmaConecta que teve 35% de aumento nas vendas após implementação.",
    methodology: "spin",
    confidence: 0.92,
    context: "Roberto Almeida está em fase de negociação e mencionou orçamento como objeção.",
  },
  {
    id: "ai-s-2",
    type: "objection",
    content: "O lead mencionou preço alto. Resposta sugerida: destacar o ROI médio de 6 meses dos clientes enterprise e oferecer plano anual com 15% de desconto.",
    methodology: "bant",
    confidence: 0.88,
    context: "Objeção de preço no estágio de negociação.",
  },
  {
    id: "ai-s-3",
    type: "next_step",
    content: "Fernanda Lima não respondeu há 24 horas. Sugiro enviar mensagem de follow-up com conteúdo educativo sobre CRM para salões de beleza.",
    methodology: "def",
    confidence: 0.85,
    context: "Lead esfriando no estágio de primeiro contato.",
  },
  {
    id: "ai-s-4",
    type: "score_explanation",
    content: "Score de 92 baseado em: empresa com +200 funcionários (+30), resposta rápida às mensagens (+20), demonstrou necessidade clara (+25), orçamento validado (+17).",
    methodology: "bant",
    confidence: 0.95,
    context: "Score detalhado do lead Roberto Almeida.",
  },
  {
    id: "ai-s-5",
    type: "response",
    content: "Eduardo perguntou sobre integração ERP. Sugiro enviar vídeo da PoC com TOTVS Protheus e agendar reunião técnica com a equipe de TI deles.",
    methodology: "spin",
    confidence: 0.90,
    context: "Lead VIP em fase avançada de negociação.",
  },
]

// ── AI Insights ─────────────────────────────────────────────────

export const mockAIInsights: AIInsight[] = [
  {
    id: "ai-i-1",
    type: "alert",
    title: "Lead quente sem atendimento",
    description: "Vanessa Moura (score 48) está sem contato há 5 horas. Leads que não recebem primeiro contato em 4 horas tem 60% menos chance de conversão.",
    severity: "warning",
    actionable: true,
    suggestedAction: "Atribuir SDR e fazer contato imediato",
    relatedEntityId: "lead-14",
    createdAt: hoursAgo(1),
  },
  {
    id: "ai-i-2",
    type: "recommendation",
    title: "Melhor horário para contato",
    description: "Análise dos últimos 30 dias mostra que leads do setor de Saúde respondem 40% mais rápido entre 10h e 12h.",
    severity: "info",
    actionable: true,
    suggestedAction: "Agendar contatos do setor de saúde pela manhã",
    createdAt: hoursAgo(6),
  },
  {
    id: "ai-i-3",
    type: "pattern",
    title: "Taxa de no-show aumentou 25%",
    description: "Nas últimas 2 semanas, a taxa de no-show subiu de 8% para 10%. A maioria dos no-shows são de leads que vieram pelo Instagram.",
    severity: "warning",
    actionable: true,
    suggestedAction: "Enviar lembrete adicional 1h antes para leads do Instagram",
    createdAt: daysAgo(1),
  },
  {
    id: "ai-i-4",
    type: "anomaly",
    title: "Queda na conversão do estágio Proposta",
    description: "A conversão de Proposta Enviada para Negociação caiu 12% esta semana. Pode estar relacionada à atualização recente dos preços.",
    severity: "critical",
    actionable: true,
    suggestedAction: "Revisar tabela de preços e alinhar com equipe comercial",
    createdAt: hoursAgo(3),
  },
  {
    id: "ai-i-5",
    type: "recommendation",
    title: "Rafael Oliveira próximo de meta",
    description: "Rafael está a R$ 12.000 de bater a meta mensal. Com 3 deals em negociação, a probabilidade de atingir é de 78%.",
    severity: "info",
    actionable: false,
    relatedEntityId: "tm-3",
    createdAt: hoursAgo(2),
  },
]

// ── Tags ────────────────────────────────────────────────────────

export const mockTags: Tag[] = [
  { id: "tag-1", name: "Enterprise", color: "#6366f1", category: "Porte" },
  { id: "tag-2", name: "PME", color: "#06b6d4", category: "Porte" },
  { id: "tag-3", name: "Urgente", color: "#ef4444", category: "Prioridade" },
  { id: "tag-4", name: "VIP", color: "#f59e0b", category: "Prioridade" },
  { id: "tag-5", name: "Quente", color: "#f97316", category: "Temperatura" },
  { id: "tag-6", name: "Frio", color: "#64748b", category: "Temperatura" },
  { id: "tag-7", name: "Inbound", color: "#22c55e", category: "Origem" },
  { id: "tag-8", name: "Outbound", color: "#8b5cf6", category: "Origem" },
  { id: "tag-9", name: "Tecnologia", color: "#3b82f6", category: "Setor" },
  { id: "tag-10", name: "Saúde", color: "#10b981", category: "Setor" },
  { id: "tag-11", name: "Educação", color: "#a855f7", category: "Setor" },
  { id: "tag-12", name: "Varejo", color: "#ec4899", category: "Setor" },
]

// ── Custom Fields ───────────────────────────────────────────────

export const mockCustomFields: CustomField[] = [
  {
    id: "cf-1",
    key: "setor",
    label: "Setor de Atuação",
    type: "text",
    required: false,
    entityType: "lead",
  },
  {
    id: "cf-2",
    key: "funcionarios",
    label: "Número de Funcionários",
    type: "number",
    required: false,
    entityType: "lead",
  },
  {
    id: "cf-3",
    key: "orcamentoAprovado",
    label: "Orçamento Aprovado",
    type: "boolean",
    required: false,
    entityType: "lead",
  },
  {
    id: "cf-4",
    key: "motivoPerda",
    label: "Motivo da Perda",
    type: "select",
    options: ["Preço", "Concorrência", "Timing", "Sem necessidade", "Sem resposta"],
    required: false,
    entityType: "lead",
  },
  {
    id: "cf-5",
    key: "planoInteresse",
    label: "Plano de Interesse",
    type: "select",
    options: ["Starter", "Pro", "Enterprise", "Custom"],
    required: false,
    entityType: "lead",
  },
]
